spring:
  jpa:
    hibernate:
    #      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: dalsom
    password: dalsom
    url: jdbc:mariadb://localhost:3306/dalsom
  h2:
    console:
      enabled: false

