spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
      database: h2
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:tcp://localhost/~/dalsom