spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  #      database: h2
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: dalsom_admin
    password: dalsom
    url: jdbc:mariadb://localhost:3306/dalsom